#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "Phonetic Similarity Poem"
description    : >
  This example project uses the phonetics library to take one poem and make another. 
long_description: |
  The poetics library uses the AStar algorithm, along with a pronunciation dictionary,
  to convert one poem into another with phonologically similar words.
time_needed: "45 minutes" # "30/45/60 minutes".


#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 2 # 1 == R, 2 == python, 3 == sql
# IDs for courses that are prerequisites
# See https://mb.datacamp.com/question/126 for IDs
prerequisites:
  - 799
difficulty_level: 2 # 1 == easy, 2 == medium, 3 == hard
# IDs for the topics the project covers
# See https://authoring.datacamp.com/projects/projects-repo-structure.html#project-yml for IDs
topics:
  - 12

#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : python # One of r, python or sql
# The name of the docker image used to run the course
from           : 'python-notebooks-prod:117'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.
